### ISSUE TITLE
Porting to BeagleBoneBlack

### ISSUE THREAD

**Issue by candronikos** [mayeranalytics/pySX127x#22]
Hi,

Attempted to run this library on the BeagleBoneBlack. Would it require a lot of work or could you point me in the direction of a project that could run on the BBB instead?

**Comment by mayeranalytics** [comment]
You have to modify `board_config.py` and adapt it to the BBB.
The  [Adafruit_Python_GPIO](https://github.com/adafruit/Adafruit_Python_GPIO) library might help you with this. In the description it says that it is "in an early stage", however.
Otherwise just use [Adafruit_BBIO](https://pypi.python.org/pypi/Adafruit_BBIO). The interface looks very similar to RPi.GPIO, you might be able to just drop it in.

In any case I suggest to get the communication working without using `pySX127x`, first. What I usually do is wire up the RPi, or whatever SBC, with the module and then issue SPI commands from the IPython shell. When I'm able to query some register, e.g. hw and fw version, I move to the next step.
